name: DontCraftItem
author: alvin0319
main: DontCraftItem\DontCraftItem
version: 1.0.0
api:
  - 4.0.0
  - 3.0.0
  - 3.5.9
  - 3.5.8
  - 3.5.7
  - 3.5.6
  - 3.5.5
description: A PocketMine-MP Plugin | DontCraftItem, made by alvin0319!